# Generated by Django 5.0.1 on 2024-01-12 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_id',
            field=models.CharField(default='alterarid', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='certificados', to='eventos.evento'),
        ),
    ]
