# Generated by Django 5.0.1 on 2024-01-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_certificado_certificado_id_alter_certificado_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
