# Generated by Django 5.0.1 on 2024-01-15 21:48

import modules.eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_certificado_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado',
            field=models.ImageField(upload_to=modules.eventos.models.pasta_certificado_evento),
        ),
    ]
