# Generated by Django 5.0.1 on 2024-01-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_certificado_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
